version: '3.8'

services:
  python:
    build:
      context: ./python
    ports:
      - 8000:8000
    volumes:
      - ./python/app:/app
    environment:
      PGDATABASE: todo_app
      PGUSER: root
      PGPASSWORD: p@ssw0rd
      PGHOST: db
      PGPORT: 5432
      PGSSLMODE: disable
    depends_on:
      db:
        condition: service_healthy
  rust:
    build:
      context: ./rust
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.2-alpine
    command: postgres
    container_name: todo-app-db
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p@ssw0rd}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data
      - data-volume:/var/log
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 3
  flyway:
    image: flyway/flyway:9.8.1-alpine
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
volumes:
  data-volume:
