version: '3.8'

services:
  python:
    build:
      context: ./python
    ports:
      - 8000:8000
    volumes:
      - ./python/app:/app
  db:
    image: postgres:14.2-alpine
    command: postgres
    container_name: todo-app-db
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p@ssw0rd}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data
      - data-volume:/var/log
  flyway:
    image: flyway/flyway:9.8.1-alpine
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db
volumes:
  data-volume:
